services:
  db:
    image: postgres:15
    container_name: thinkroyal-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: thinkroyal_finance
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
